flags = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

common_all = COMMON/commandsNames.h

common_cpp = COMMON/commonFunctions.cpp

proc_cpp = PROCESSOR/main.cpp PROCESSOR/executableCommands.cpp PROCESSOR/stackFunctions.cpp PROCESSOR/processorFunctions.cpp

proc_all = PROCESSOR/stackFunctions.h PROCESSOR/executableCommands.h PROCESSOR/structAndEnums.h PROCESSOR/processorFunctions.h $(proc_cpp)

asmb_cpp = ASSEMBLER/mainAssembler.cpp ASSEMBLER/assemblerFunctions.cpp ASSEMBLER/textTools.cpp PROCESSOR/executableCommands.cpp PROCESSOR/stackFunctions.cpp PROCESSOR/processorFunctions.cpp

asmb_all = ASSEMBLER/assemblerFunctions.h ASSEMBLER/textStructs.h ASSEMBLER/textTools.h ASSEMBLER/structAssembler.h $(asmb_cpp)

disasmb_cpp = DISASSEMBLER/mainDisassembler.cpp DISASSEMBLER/disassemblerFunctions.cpp

disasmb_all = ASSEMBLER/disassemblerFunctions.h $(disasmb_cpp)

text_file = TEXT_FILE/bin_code.bin TEXT_FILE/input.txt TEXT_FILE/text_code.asm

processor: $(proc_cpp) $(proc_headers) $(common_headers)
	@echo -------------------------------------------------------------------------
	g++ $(proc_cpp) $(common_cpp) $(flags) -o EXE/processor.exe

assembler: $(asmb_cpp) $(asmb_headers) $(common_headers)
	@echo -------------------------------------------------------------------------
	g++ $(asmb_cpp) $(common_cpp) $(flags) -o EXE/assembler.exe

disassembler: $(disasmb_cpp) $(disasmb_headers) $(common_headers)
	@echo -------------------------------------------------------------------------
	g++ $(disasmb_cpp) $(common_cpp) $(flags) -o EXE/disassembler.exe

run-a:
	./EXE/assembler.exe

run-d:
	./EXE/disassembler.exe

run-p:
	./EXE/processor.exe
