const int NUMBER_OF_COMMANDS = 27;

struct command commandsArray[NUMBER_OF_COMMANDS] = { { "",        emptyString,      noArg,     &errorMessageFunc,  getCommandHash("")        },
                                                     { "PUSH",    PUSHcmd,          numArg,    &pushFunc,          getCommandHash("PUSH")    },
                                                     { "ADD",     ADDcmd,           noArg,     &calcFunc,          getCommandHash("ADD")     },
                                                     { "SUB",     SUBcmd,           noArg,     &calcFunc,          getCommandHash("SUB")     },
                                                     { "MUL",     MULcmd,           noArg,     &calcFunc,          getCommandHash("MUL")     },
                                                     { "DIV",     DIVcmd,           noArg,     &calcFunc,          getCommandHash("DIV")     },
                                                     { "POW",     POWcmd,           noArg,     &calcFunc,          getCommandHash("POW")     },
                                                     { "SQRT",    SQRTcmd,          noArg,     &sqrtFunc,          getCommandHash("SQRT")    },
                                                     { "OUT",     OUTcmd,           noArg,     &outFunc,           getCommandHash("OUT")     },
                                                     { "HLT",     HLTcmd,           noArg,     &hltFunc,           getCommandHash("HLT")     },
                                                     { "PUSHREG", PUSHREGcmd,       regArg,    &pushFunc,          getCommandHash("PUSHREG") },
                                                     { "POPREG",  POPREGcmd,        regArg,    &popFunc,           getCommandHash("POPREG")  },
                                                     { "IN",      INcmd,            noArg,     &inFunc,            getCommandHash("IN")      },
                                                     { "JMP",     JMPcmd,           labelArg,  &jumpAndCallFunc,   getCommandHash("JMP")     },
                                                     { "JB",      JBcmd,            labelArg,  &comparingJumpFunc, getCommandHash("JB")      },
                                                     { "JBE",     JBEcmd,           labelArg,  &comparingJumpFunc, getCommandHash("JBE")     },
                                                     { "JA",      JAcmd,            labelArg,  &comparingJumpFunc, getCommandHash("JA")      },
                                                     { "JAE",     JAEcmd,           labelArg,  &comparingJumpFunc, getCommandHash("JAE")     },
                                                     { "JE",      JEcmd,            labelArg,  &comparingJumpFunc, getCommandHash("JE")      },
                                                     { "JNE",     JNEcmd,           labelArg,  &comparingJumpFunc, getCommandHash("JNE")     },
                                                     { "CALL",    CALLcmd,          labelArg,  &jumpAndCallFunc,   getCommandHash("CALL")    },
                                                     { "RET",     RETcmd,           noArg,     &retFunc,           getCommandHash("RET")     },
                                                     { "PUSHM",   PUSHMcmd,         regArg,    &pushFunc,          getCommandHash("PUSHM")   },
                                                     { "POPM",    POPMcmd,          regArg,    &popFunc,           getCommandHash("POPM")    },
                                                     { "MOD",     MODcmd,           regArg,    &calcFunc,          getCommandHash("MOD")     },
                                                     { "DRAW",    DRAWcmd,          noArg,     &drawFunc,          getCommandHash("DRAW")    },
                                                     { "ERROR",   ERROR_COMMANDcmd, noArg,     &errorMessageFunc,  getCommandHash("ERROR")   } };

