const int NUMBER_OF_COMMANDS = 26;
struct comand comandsArray[NUMBER_OF_COMMANDS] = { {"", emptyString, noArg},
                                                   {"PUSH", PUSHcmd, numArg,},
                                                   {"ADD", ADDcmd, noArg},
                                                   {"SUB", SUBcmd, noArg},
                                                   {"MUL", MULcmd, noArg},
                                                   {"DIV", DIVcmd, noArg},
                                                   {"POW", POWcmd, noArg},
                                                   {"SQRT", SQRTcmd, noArg},
                                                   {"OUT", OUTcmd, noArg},
                                                   {"HLT", HLTcmd, noArg},
                                                   {"PUSHREG", PUSHREGcmd, regArg},
                                                   {"POPREG", POPREGcmd, regArg},
                                                   {"IN", INcmd, noArg},
                                                   {"JMP", JMPcmd, labelArg},
                                                   {"JB", JBcmd, labelArg},
                                                   {"JBE", JBEcmd, labelArg},
                                                   {"JA", JAcmd, labelArg},
                                                   {"JAE", JAEcmd, labelArg},
                                                   {"JE", JEcmd, labelArg},
                                                   {"JNE", JNEcmd, labelArg},
                                                   {"CALL", CALLcmd, labelArg},
                                                   {"RET", RETcmd, noArg},
                                                   {"PUSHM", PUSHMcmd, regArg},
                                                   {"POPM", POPMcmd, regArg},
                                                   {"MOD", MODcmd, regArg},
                                                   {"ERROR", ERROR_COMMANDcmd, noArg} };
