struct command commandsArray[] = { { "",        emptyString,      noArg,     &errorMessageFunc,  getStringHash("")         },
                                   { "PUSH",    PUSHcmd,          numArg,    &pushFunc,          getStringHash("PUSH")     },
                                   { "ADD",     ADDcmd,           noArg,     &calcFunc,          getStringHash("ADD")      },
                                   { "SUB",     SUBcmd,           noArg,     &calcFunc,          getStringHash("SUB")      },
                                   { "MUL",     MULcmd,           noArg,     &calcFunc,          getStringHash("MUL")      },
                                   { "DIV",     DIVcmd,           noArg,     &calcFunc,          getStringHash("DIV")      },
                                   { "POW",     POWcmd,           noArg,     &calcFunc,          getStringHash("POW")      },
                                   { "SQRT",    SQRTcmd,          noArg,     &sqrtFunc,          getStringHash("SQRT")     },
                                   { "OUT",     OUTcmd,           noArg,     &outFunc,           getStringHash("OUT")      },
                                   { "HLT",     HLTcmd,           noArg,     &hltFunc,           getStringHash("HLT")      },
                                   { "PUSHREG", PUSHREGcmd,       regArg,    &pushFunc,          getStringHash("PUSHREG")  },
                                   { "POPREG",  POPREGcmd,        regArg,    &popFunc,           getStringHash("POPREG")   },
                                   { "IN",      INcmd,            noArg,     &inFunc,            getStringHash("IN")       },
                                   { "JMP",     JMPcmd,           labelArg,  &jumpAndCallFunc,   getStringHash("JMP")      },
                                   { "JB",      JBcmd,            labelArg,  &comparingJumpFunc, getStringHash("JB")       },
                                   { "JBE",     JBEcmd,           labelArg,  &comparingJumpFunc, getStringHash("JBE")      },
                                   { "JA",      JAcmd,            labelArg,  &comparingJumpFunc, getStringHash("JA")       },
                                   { "JAE",     JAEcmd,           labelArg,  &comparingJumpFunc, getStringHash("JAE")      },
                                   { "JE",      JEcmd,            labelArg,  &comparingJumpFunc, getStringHash("JE")       },
                                   { "JNE",     JNEcmd,           labelArg,  &comparingJumpFunc, getStringHash("JNE")      },
                                   { "CALL",    CALLcmd,          labelArg,  &jumpAndCallFunc,   getStringHash("CALL")     },
                                   { "RET",     RETcmd,           noArg,     &retFunc,           getStringHash("RET")      },
                                   { "PUSHM",   PUSHMcmd,         ramArg,    &pushFunc,          getStringHash("PUSHM")    },
                                   { "POPM",    POPMcmd,          ramArg,    &popFunc,           getStringHash("POPM")     },
                                   { "MOD",     MODcmd,           noArg,     &calcFunc,          getStringHash("MOD")      },
                                   { "DRAW",    DRAWcmd,          noArg,     &drawFunc,          getStringHash("DRAW")     },
                                   { "UPDATE",  UPDATEcmd,        noArg,     &updateFunc,        getStringHash("UPDATE")   },
                                   { "ERROR",   ERROR_COMMANDcmd, noArg,     &errorMessageFunc,  getStringHash("ERROR")    } };

const int NUMBER_OF_COMMANDS = sizeof(commandsArray) / sizeof(struct command);
